### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by Dede-Git** [nss-evening-cohort-21/rare_v2_server#44]

**Comment by erin-stephens** [comment]
As a user I would like to be able to logout of the system so that I can ensure that no one else who uses my computer will have access to my Rare account.

Given an authenticated user is in the Rare application
When they select the Logout option from the menu
Then they should be logged out of the system
And they should be directed to the home page

**Comment by allison-blumenthal** [comment]
- [ ] Backend
- [ ] Frontend
